// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	big "math/big"

	mock "github.com/stretchr/testify/mock"
)

// Multiplicator is an autogenerated mock type for the Multiplicator type
type Multiplicator struct {
	mock.Mock
}

// Multiply provides a mock function with given fields: a, b
func (_m *Multiplicator) Multiply(a int64, b int64) (*big.Int, error) {
	ret := _m.Called(a, b)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(int64, int64) *big.Int); ok {
		r0 = rf(a, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = rf(a, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
